### PR TITLE
Added translation for NOI2014A

### PR DESCRIPTION
**Pull request by DragoPhoenix**
Check Constraints and NOTE at the end.

### CODE REVIEW

**Comment by Macesuted** [comment]
What's the English title of this problem?

**Comment by Macesuted** [comment]
Should I write `Decimal 5` or `Binary 5` in the NOTE section to indicate that this binary number is in decimal 5?

**Comment by DragoPhoenix** [comment]
English Title is Difficulty getting up syndrome
`Binary representation of 5` would perhaps make it clear.

**Comment by Macesuted** [comment]
And what's the English title of NOI2014B? :sweat:

**Comment by Macesuted** [comment]
Thanks!

**Pull request merged**
